# we only need to point to python for the tests to run
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r travis_requirements

# command to run tests
script: nosetests extras/validatesymbtr.py

